projects:
  storefront:
    schema: 'node_modules/@shopify/hydrogen/storefront.schema.json'
    documents:
      - 'app/graphql/storefront/**/*.{ts,tsx,js,jsx}'
  customer-account:
    schema: 'node_modules/@shopify/hydrogen/customer-account.schema.json'
    documents:
      - 'app/graphql/customer-account/**/*.{ts,tsx,js,jsx}'
